version: '2'
services:
  webserver:
    image: webdevops/php-apache-dev:latest
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./:/var/www/html
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_ALIAS_DOMAIN: fmapts.demo
      XDEBUG_REMOTE_HOST: remote_host=host.docker.internal



